services:
  axmipic:
    image: ghcr.io/axmishell/axmipic:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - axmipic-data:/app/data
      - axmipic-config:/app/configs

volumes:
  axmipic-data:
  axmipic-config:
