// Package storage defines the object storage abstraction used by AXmiPic.
package storage

import (
	"context"
	"errors"
	"io"
	"time"
)

// ErrNotFound is returned when the requested object does not exist.
var ErrNotFound = errors.New("storage: object not found")

// ErrInvalidKey is returned when a storage key is malformed or unsafe.
var ErrInvalidKey = errors.New("storage: invalid key")

// ObjectInfo describes a stored object's metadata.
type ObjectInfo struct {
	Key         string
	Size        int64
	ContentType string
}

// Storage stores and serves image objects. Implementations must be safe for
// concurrent use. Keys are slash-separated relative paths generated by the
// application, never user input.
type Storage interface {
	Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error
	Get(ctx context.Context, key string) (io.ReadCloser, error)
	Delete(ctx context.Context, key string) error
	Exists(ctx context.Context, key string) (bool, error)
	URL(key string) string
	Stat(ctx context.Context, key string) (*ObjectInfo, error)
}

// PresignOptions constrains a direct-to-storage upload.
type PresignOptions struct {
	// ContentType is the exact media type the client must send.
	ContentType string
	// AllowedContentTypes is used by backends that accept a media type pattern.
	AllowedContentTypes []string
	// MaxSize is the maximum accepted object size in bytes.
	MaxSize int64
	// Expires is how long the presigned request stays valid.
	Expires time.Duration
}

// PresignedRequest describes how a client should upload an object directly to
// the storage backend.
type PresignedRequest struct {
	URL       string
	Method    string
	Fields    map[string]string
	Headers   map[string]string
	ExpiresAt time.Time
}

// Presigner is implemented by backends that support direct client uploads.
// Backends that do not (for example local storage) are detected with a type
// assertion and reported as unsupported.
type Presigner interface {
	PresignPut(ctx context.Context, key string, opts PresignOptions) (*PresignedRequest, error)
}
